# Generated by Django 5.2 on 2025-04-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200, verbose_name='Номи хизмат')),
                ('tavsif', models.TextField(verbose_name='Тавсифи хизмат')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нархи хизмат (сомонӣ)')),
                ('joylashuv', models.CharField(max_length=200, verbose_name='Ҷойгиршавӣ')),
                ('telefon', models.CharField(max_length=20, verbose_name='Рақами телефон')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Вақти илова кардан')),
            ],
        ),
    ]
