# Generated by Django 5.2 on 2025-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0002_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='joylashuv',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ҷойгиршавӣ'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нархи хизмат (сомонӣ)'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рақами телефон'),
        ),
    ]
