# Generated by Django 5.2 on 2025-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0003_delete_service_alter_xizmat_joylashuv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmat',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='xizmatlar/'),
        ),
    ]
