# Generated by Django 5.2 on 2025-04-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0005_xizmat_user_alter_xizmat_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(choices=[('Qurilish', 'Qurilish'), ('Tamirlash', 'Tamirlash'), ('O‘qitish', 'O‘qitish'), ('Transport', 'Transport'), ('Elektrik', 'Elektrik'), ('Bog‘bonlik', 'Bog‘bonlik'), ('Boshqa', 'Boshqa')], default='Boshqa', max_length=50),
        ),
    ]
