# Generated by Django 5.2 on 2025-04-29 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0006_xizmat_kategoriya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='joylashuv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(blank=True, default='Дигар', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='nomi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='xizmatlar_rasmlar/'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='tavsif',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Sharh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField()),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xizmatlar.xizmat')),
            ],
        ),
    ]
