# Generated by Django 5.2 on 2025-04-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0007_alter_xizmat_joylashuv_alter_xizmat_kategoriya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharh',
            name='xizmat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharhlar', to='xizmatlar.xizmat'),
        ),
    ]
