# Generated by Django 5.2 on 2025-04-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0008_alter_sharh_xizmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharh',
            name='xizmat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xizmatlar.xizmat'),
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(choices=[('boshqa', 'Бошқа'), ('transport', 'Транспорт'), ('repair', 'Ремонт')], default='boshqa', max_length=20),
        ),
    ]
