# Generated by Django 5.2 on 2025-04-30 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0009_alter_sharh_xizmat_alter_xizmat_kategoriya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharh',
            name='xizmat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharhlar', to='xizmatlar.xizmat'),
        ),
    ]
