# Generated by Django 5.2 on 2025-04-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0010_alter_sharh_xizmat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(blank=True, default='Дигар', max_length=100, null=True),
        ),
    ]
