# Generated by Django 5.2 on 2025-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0012_availability_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(blank=True, choices=[('boshqa', 'Бошқа'), ('transport', 'Транспорт'), ('repair', 'Ремонт')], default='boshqa', max_length=100, null=True),
        ),
    ]
