# Generated by Django 5.2 on 2025-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0013_kategoriya_alter_xizmat_kategoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmat',
            name='skidka',
            field=models.BooleanField(default=False),
        ),
    ]
