# Generated by Django 5.2 on 2025-05-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0014_xizmat_skidka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='kategoriya',
            field=models.CharField(blank=True, choices=[('Сантехник', 'Сантехник'), ('Қассоб', 'Қассоб'), ('Тозакунанда', 'Тозакунанда'), ('Барқчӣ', 'Барқчӣ'), ('Ҳашарчӣ', 'Ҳашарчӣ')], default='Дигар', max_length=100, null=True),
        ),
    ]
