# Generated by Django 5.2 on 2025-05-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0015_alter_xizmat_kategoriya'),
    ]

    operations = [
        migrations.AddField(
            model_name='xizmat',
            name='nohiya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
