# Generated by Django 5.2 on 2025-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0016_xizmat_nohiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='nohiya',
            field=models.CharField(choices=[('Dushanbe', 'Душанбе'), ('Khujand', 'Хуҷанд'), ('Kulob', 'Кӯлоб'), ('Bokhtar', 'Бохтар'), ('Hisor', 'Ҳисор'), ('Istaravshan', 'Истаравшан'), ('Panjakent', 'Панҷакент'), ('Tursunzoda', 'Турсунзода'), ('Khorugh', 'Хоруғ'), ('Other', 'Дигар')], default='Other', max_length=50),
        ),
    ]
