# Generated by Django 5.2 on 2025-05-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0017_alter_xizmat_nohiya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xizmat',
            name='joylashuv',
        ),
    ]
