# Generated by Django 5.2 on 2025-05-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmatlar', '0018_remove_xizmat_joylashuv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xizmat',
            name='nohiya',
            field=models.CharField(choices=[('Душанбе', 'Душанбе'), ('Хуҷанд', 'Хуҷанд'), ('Кӯлоб', 'Кӯлоб'), ('Бохтар', 'Бохтар'), ('Ҳисор', 'Ҳисор'), ('Истаравшан', 'Истаравшан'), ('Панҷакент', 'Панҷакент'), ('Турсунзода', 'Турсунзода'), ('Хоруғ', 'Хоруғ'), ('Дигар', 'Дигар')], default='Дигар', max_length=50),
        ),
    ]
